### ISSUE TITLE
[Bug]: Elmo player model always in T-Pose

### ISSUE THREAD

**Issue by Ecorte** [Quebec-Games/issues#13]
### Which server is this bug report for?

All

### Issue description

_(The playermodel is currently disabled on the servers 
because of this bug)_
1. Equip the `Elmo` playermodel.

### Expected Behavior

It you should work like any playermodel.

### Current Behavior

It stays in T-Pose causing weapon to not be shown.

**Comment by Dimentio** [comment]
Went ahead and just deleted the model.
