### ISSUE TITLE
[Bug]: Glorified bonus not working

### ISSUE THREAD

**Issue by Calimbita** [Quebec-Games/issues#15]
### Which server is this bug report for?

All

### Issue description

Glorified desc states that it gives a boost of points when you kill with a Legendary or Mythical weapon. However, it doesn't give a boost when using a Mythical weapon.

### Expected Behavior

Getting more points when you use glorified and a mythical weapon.

### Current Behavior

You don't get more points (doesn't work).

**Comment by Ecorte** [comment]
The effect only applies if you have the weapon **in your hand** are you sure it isn't just that ?

**Comment by Calimbita** [comment]
> The effect only applies if you have the weapon **in your hand** are you sure it isn't just that ?

Yeah since I alr tested it (on Doki but should be the same in all servers) with both legendary and mythical weapons, and with a Legendary it works fine but with a mythical is not the same so probably an error

**Comment by Ecorte** [comment]
After some testing this is the conclusion:

- Holding a mythic rated weapon **does not** give the `200%` bonus points but instead only give `100%`.
- Holding a legendary rated weapon give the `100%` as intented.

**Comment by Dimentio** [comment]
Fixed!
