### ISSUE TITLE
[Bug]: The footsteps of players other than the murderer are not showing

### ISSUE THREAD

**Issue by HimeChanArisu** [Quebec-Games/issues#16]
### Which server is this bug report for?

All

### Issue description

1.) Change footstep lifetime to a value other than 0
2.) Get a murderer round
3.) Look at the ground while players are moving during this murderer round

### Expected Behavior

The appearance of a coloured footstep texture on the ground where a player has stepped

### Current Behavior

The appearance of a coloured footstep texture on the ground only where the murderer has stepped

### Screenshots/Videos

https://user-images.githubusercontent.com/110792821/183514627-70f7c3cc-2f63-454f-be8c-cf3fe88d8e33.mp4

**Comment by Dimentio** [comment]
Fixed !
