### ISSUE TITLE
[Bug]: Jump boost blessing effect removing itself randomly

### ISSUE THREAD

**Issue by StarFishhy** [Quebec-Games/issues#24]
### Which server is this bug report for?

All

### Issue description

I'll post a clip of it in #support since the file is too big to upload on here

### Expected Behavior

Jump Boost Blessing gives you extra jump height for 60 seconds

### Current Behavior

Randomly disables itself before the 60 seconds is up

**Comment by Ecorte** [comment]
Clip: https://cdn.discordapp.com/attachments/594006765046202368/1030988214409900112/Garrysmod_2022.10.16_-_00.30.36.02.DVR_Trim.mp4

**Comment by Dimentio** [comment]
Fixed!
