### ISSUE TITLE
[Bug]: Weekly ranking hasn't reset

### ISSUE THREAD

**Issue by Kaita01** [Quebec-Games/issues#25]
### Which server is this bug report for?

All

### Issue description

1. Get top 3 in weekly ranking
2. Wait for weekly ranking to reset
3. It doesn't

### Expected Behavior

Weekly rewards to be given and reset.

### Current Behavior

Weekly rewards are not given and hasn't reset.

### Screenshots/Videos

![Weekly](https://user-images.githubusercontent.com/99235807/200344946-9aa733ae-ee9e-450f-b05a-183cd04943a4.PNG)
11/7/2022

**Comment by Ecorte** [comment]
Fixed
