### ISSUE TITLE
[Bug]: Webley revolver not working

### ISSUE THREAD

**Issue by Stormlux** [Quebec-Games/issues#31]
### Which server is this bug report for?

All

### Issue description

The Webley revolver seem to be broken at the moment when you :

1°) Try to use the gun in Ghost mod.
2°) Use the gun as a Sherif Weapon.
3°) Use the Alternate button.

### Expected Behavior

The gun shoot a bullet and kill the other player.

### Current Behavior

- No Ammo "sound". 
- Nothing happen.

### Screenshots/Videos

https://github.com/Quebec-Games/issues/assets/133585127/6a02345e-d8a4-4bac-8153-e92d5827dff8

**Comment by Dimentio** [comment]
Fixed!
