### ISSUE TITLE
[Bug]: Revolver R8 Curse skin is broken

### ISSUE THREAD

**Issue by Laserfull** [Quebec-Games/issues#33]
### Which server is this bug report for?

All

### Issue description

The Revolver R8 Curse skin is broken
1.ITS ALL BLACK
2. IT USED TO HAVE COOL COLORS

### Expected Behavior

Cool pattern

### Current Behavior

blackface justin trudeau looking ass gun

### Screenshots/Videos

![image](https://github.com/Quebec-Games/issues/assets/121707378/441683a6-f139-461c-86b0-7600033bedec)

**Comment by Ecorte** [comment]
Fixed
