### ISSUE TITLE
[Bug]: Accessories not working

### ISSUE THREAD

**Issue by Ecorte** [Quebec-Games/issues#6]
### Which server is this bug report for?

All

### Issue description

1. Equip an accessory (that isn't included in the base game.)

### Expected Behavior

You should be able to see to accessory in-game.

### Current Behavior

You see a can instead.

**Comment by Dimentio** [comment]
Which accessories?

**Comment by Ecorte** [comment]
https://docs.google.com/document/d/1jZSXJHv-mLPfo5yg79R-u_q0NO-ZRMiBrnYr7xRENs4/edit?usp=sharing
Here's a list with the addons

**Comment by Dimentio** [comment]
These are all already included, gmod is being gmod again I recommend verifying integrity that should fix most of these issues.
